name: studrink
description: A new Flutter application.
publish_to: 'none'
version: 1.0.1+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  provider: ^6.0.3
  rxdart: ^0.27.5
  flutter_svg: ^1.1.1+1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  random_color: ^1.0.5
  material_design_icons_flutter: ^5.0.6996
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  back_button_interceptor: ^6.0.1
  tuple: ^2.0.0
  image: ^3.2.0
  avatar_glow: ^2.0.2
  qr_code_scanner: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  bloc_test: ^8.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/games/
    - assets/screenshots/
