name: ptit_godet
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  mockito: ^4.1.3
  bloc_test: ^7.0.6
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+2
  overlay: ^0.0.1
  photo: ^0.4.8
  image_picker: ^0.6.7+17
  image_cropper: ^1.2.1
  random_color: ^1.0.5
  material_design_icons_flutter: ^4.0.5755

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pp_.png
    - assets/games/
    - assets/screenshots/
