name: studrink
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  provider: ^6.0.0
  rxdart: ^0.27.1
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.7
  image_picker: ^0.8.3+3
  image_cropper: ^1.4.1
  random_color: ^1.0.6-nullsafety
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  url_launcher: ^6.0.9
  back_button_interceptor: ^5.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  bloc_test: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/games/
    - assets/screenshots/
